#!/bin/sh

case "$1" in
start)
    echo "Loading aesd-char-device module"
    /usr/bin/aesdchar_load
    ;;
stop)
    echo "Unloading scull module"
    /usr/bin/aesdchar_unload
    ;;
*)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac

exit 0
